server:
  port: 8082

spring:
  application:
    name: marakogr-kafka-test

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health, prometheus'
  endpoint:
    health:
      enable: true
      show-details: always
    metrics:
      enable: true
    prometheus:
      enabled: true

# Профиль для включенной кафки
---
spring:
  config:
    activate:
      on-profile: kafka
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    auto:
      offset:
        reset: latest
kafka:
  group_id:
    prefix:
      generation: false
  logging:
    producers:
      enabled: true
  topics:
    my: my-topic
  groups:
    my: my-group

# Профиль для докера
---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    bootstrap-servers: kafka-1:29092,kafka-2:29093,kafka-3:29094