spring:
  profiles:
    active: kafka
  kafka:
    bootstrap-servers: localhost:9091
    auto:
      offset:
        reset: latest

kafka:
  group_id:
    prefix:
      generation: false
  logging:
    producers:
      enabled: true
  topics:
    my: my-topic
  groups:
    my: my-group

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: 'health, prometheus'
  endpoint:
    health:
      enable: true
      show-details: always
    metrics:
      enable: true
    prometheus:
      enabled: true

#'docker' profile only
---
#spring section
spring:
  profiles:
    active: docker,kafka
  application:
    name: marakogr-kafka-test
  kafka:
    bootstrap-servers: kafka:19091